kind: pipeline
type: docker
name: v8-mongodb-amd64

environment:
  MONGODB_VERSION: 8.2.4

trigger:
  branch:
    - '8'
  event:
    - pull_request

# Build the docker image for amd64 architecture (PR validation only)
steps:
  - name: mongodb-image-build-amd64
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platforms:
        - linux/amd64
      repo: kernel528/mongodb-community-server
      tags:
        - '${MONGODB_VERSION}-pr-${DRONE_PULL_REQUEST}-amd64'
      dry_run: true

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
---

kind: pipeline
type: docker
name: main-mongodb-amd64

environment:
  MONGODB_VERSION: 8.2.4

trigger:
  event:
    - push
    - tag
  branch:
    - main

# Build the docker image for the main branch & tagged release
steps:
  - name: main-docker-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - push
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/mongodb-community-server
      tags:
        - latest
        - '8'
        - '${MONGODB_VERSION}'
        - '${MONGODB_VERSION}-drone-build-${DRONE_BUILD_NUMBER}-amd64'

  - name: main-docker-image-build-tag
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/mongodb-community-server
      tags:
        - '${DRONE_TAG}'

  # Test docker image
  - name: latest-mongodb-amd64-test
    image: kernel528/mongodb-community-server:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - 'cat /etc/os-release'
      - 'mongod --version'
      - 'mkdir -p /tmp/mongo-data'
      - 'mongod --dbpath /tmp/mongo-data --bind_ip 127.0.0.1 --fork --logpath /tmp/mongod.log'
      - 'mongosh --quiet --eval "db.runCommand({ ping: 1 })"'
      - 'mongosh --quiet --eval "db.smoke.insertOne({ ok: 1 }); printjson(db.smoke.findOne({ ok: 1 }))"'
      - 'mongod --shutdown --dbpath /tmp/mongo-data'

  - name: mongo-seed-smoke-test
    image: kernel528/mongodb-community-server:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - 'mkdir -p /tmp/mongo-data /collections'
      - 'cp -R mongo-seed/collections/* /collections/'
      - 'mongod --dbpath /tmp/mongo-data --bind_ip 127.0.0.1 --fork --logpath /tmp/mongod.log'
      - 'export MONGO_URI="mongodb://127.0.0.1:27017/seed"'
      - 'bash mongo-seed/init.sh'
      - "mongosh --quiet --eval \"printjson(db.getSiblingDB('seed').getCollectionNames())\""
      - 'mongod --shutdown --dbpath /tmp/mongo-data'

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
