version: '3'
services:
  myapplication:
    image: mongodb/mongodb-community-server:8.0.4-ubuntu2204
    environment:
      - CONN_STR=mongodb://joe:pass@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:8.0.4-ubuntu2204
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
